// <auto-generated />
using System;
using DAW_Procesos_Fabricacion_KevinRodriguez.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAW_Procesos_Fabricacion_KevinRodriguez.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("DAW_Procesos_Fabricacion_KevinRodriguez.Models.OrdenProceso", b =>
                {
                    b.Property<int>("OrdenProduccionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcesoFabricacionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateOnly?>("FechaCompletado")
                        .HasColumnType("TEXT");

                    b.HasKey("OrdenProduccionId", "ProcesoFabricacionId");

                    b.HasIndex("ProcesoFabricacionId");

                    b.ToTable("OrdenesProcesos", (string)null);
                });

            modelBuilder.Entity("DAW_Procesos_Fabricacion_KevinRodriguez.Models.OrdenProduccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaEntregaEstimada")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeloCalzado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroOrden")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("NumeroOrden")
                        .IsUnique();

                    b.ToTable("OrdenesProduccion", (string)null);
                });

            modelBuilder.Entity("DAW_Procesos_Fabricacion_KevinRodriguez.Models.ProcesoFabricacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("ProcesosFabricacion", (string)null);
                });

            modelBuilder.Entity("DAW_Procesos_Fabricacion_KevinRodriguez.Models.OrdenProceso", b =>
                {
                    b.HasOne("DAW_Procesos_Fabricacion_KevinRodriguez.Models.OrdenProduccion", "OrdenProduccion")
                        .WithMany("Procesos")
                        .HasForeignKey("OrdenProduccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAW_Procesos_Fabricacion_KevinRodriguez.Models.ProcesoFabricacion", "ProcesoFabricacion")
                        .WithMany("Ordenes")
                        .HasForeignKey("ProcesoFabricacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenProduccion");

                    b.Navigation("ProcesoFabricacion");
                });

            modelBuilder.Entity("DAW_Procesos_Fabricacion_KevinRodriguez.Models.OrdenProduccion", b =>
                {
                    b.Navigation("Procesos");
                });

            modelBuilder.Entity("DAW_Procesos_Fabricacion_KevinRodriguez.Models.ProcesoFabricacion", b =>
                {
                    b.Navigation("Ordenes");
                });
#pragma warning restore 612, 618
        }
    }
}
